# vim:ft=kitty

## name: Discord ST





background                #000000
foreground                #ffffff

selection_background      #cccccc
selection_foreground      #555555

url_color                 #1a5fb4

wayland_titlebar_color    system
macos_titlebar_color      system

cursor                    #46c8c0
cursor_text_color         #000000

active_border_color       #1e1e1e
inactive_border_color     #282828
bell_border_color         #ed333b
visual_bell_color         none

active_tab_background     #101010
active_tab_foreground     #fcfcfc
inactive_tab_background   #1c1c1c
inactive_tab_foreground   #b0afac
tab_bar_background        none
tab_bar_margin_color      none

color0                    #1B1B1B
color1                    #6673bf
color2                    #3ea290
color3                    #b0ead9

color4                    #31658c
color5                    #596196
color6                    #8292b2
color7                    #c8cacc

color8                    #4d4d4d
color9                    #899aff
color10                   #52ad91
color11                   #98c9bb

color12                   #477ab3
color13                   #7882bf
color14                   #95a7cc
color15                   #edeff2
