# vim:ft=kitty

## name: Monochrome Cyan ST





background                #003340
foreground                #00ccff

selection_background      #ebdbb2
selection_foreground      #555555

url_color                 #1a5fb4

wayland_titlebar_color    system
macos_titlebar_color      system

cursor                    #00ccff
cursor_text_color         #000000

active_border_color       #00ccff
inactive_border_color     #282828
bell_border_color         #ed333b
visual_bell_color         none

active_tab_background     #00ccff
active_tab_foreground     #fcfcfc
inactive_tab_background   #1c1c1c
inactive_tab_foreground   #b0afac
tab_bar_background        none
tab_bar_margin_color      none

color0                    #003340
color1                    #00ccff
color2                    #00ccff
color3                    #00ccff

color4                    #00ccff
color5                    #00ccff
color6                    #00ccff
color7                    #00ccff

color8                    #00ccff
color9                    #00ccff
color10                   #00ccff
color11                   #00ccff

color12                   #00ccff
color13                   #00ccff
color14                   #00ccff
color15                   #00ccff
